public class NS_IntegParams {
private String userId;
private String classCode;
private String stationCode;   
private String servingRoad;
private String equipInt;
private String equipNr;
private String waybillSrNr;
private String goodSpell;
private String wonLaneReqID;
private String equipmentID;
private String primaryCust;
private String renewalId; 
private String expDate;
    public void setexpDate(String expDate){
        this.expDate=expDate;
    }
    public String getexpDate(){
        return expDate;
    }
    public void setrenewalId(String renewalId){
        this.renewalId=renewalId;
    }
    public String getrenewalId(){
        return renewalId;
    }
    public void setprimaryCust(String primaryCust){
        this.primaryCust=primaryCust;
    }
    public String getprimaryCust(){
        return primaryCust;
    }
    
    public void setequipmentID(String equipmentID){
        this.equipmentID=equipmentID;
    }
    public String getequipmentID(){
        return equipmentID;
    }
    
    public void setwonLaneReqID(String wonLaneReqID){
        this.wonLaneReqID=wonLaneReqID;
    }
    public String getwonLaneReqID(){
        return wonLaneReqID;
    }
    
    public void setGoodSpell(String goodSpell){
        this.goodSpell=goodSpell;
    }
    public String getGoodSpell(){
        return goodSpell;
    }

    public void setUserId(String userId){
        this.userId=userId;
    }
    public String getUserId(){
        return userId;
    }
    public void setClassCode(String classCode){
        this.classCode=classCode;
    }
    public String getClassCode(){
        return classCode;
    }
    public void setStationCode(String stationCode){
        this.stationCode=stationCode;
    }
    public String getstationCode(){
        return stationCode;
    }
    public void setServingRoad(String servingRoad){
        this.servingRoad=servingRoad;
    }
    public String getServingRoad(){
        return servingRoad;
    }
    public void setEquipInt(String equipInt){
        this.equipInt=equipInt;
    }
    public String getEquipInt(){
        return equipInt;
    }
    public void setEquipNr(String equipNr){
        this.equipNr=equipNr;
    }
    public String getEquipNr(){
        return equipNr;
    }
    public void setWaybillSrNr(String waybillSrNr){
        this.waybillSrNr=waybillSrNr;
    }
    public String getWaybillSrNr(){
        return waybillSrNr;
    }
}