/*======================================================================================================
* @Class Name : NSSales_ParsingConstants
* @author : Accenture
* @Purpose: This class is used to declare constants used for parsing the rest responses.
* @created date: 20-06-2019
* @Change Logs:                                 
----------------------------------------------------------------------------------------------------------
Developer name        Date          Description        
----------------------------------------------------------------------------------------------------------
@Pranay Banerjee      20-06-2019    Request No.   , Phase-II
@Arjun Ghosh		  24-06-2019    Added public access modifier to the constants that were already declared, along with this doumentation
==========================================================================================================*/
public class NSSales_ParsingConstants {
    
    /*Parsing Constants*/
    public Static Final String ROWS = 'rows';
    /*Parsing Constants*/
    public Static Final String VALS = 'vals';
    /*Parsing Constants*/
    public Static Final String VAL = 'val';
    /*Parsing Constants*/
    public Static Final String CSS_CLASS = 'cssClass';
    /*Parsing Constants*/
    public Static Final String HEADER = 'headers';
    /*Parsing Constants*/
    public Static Final String TITLE = 'title';
    /*Parsing Constants*/
    public Static Final String BlANK = '';
    /*Parsing Constants*/
    public Static Final String H_FIELDS ='hiddenflds';
    
}