public class NSSales_NPOConstants {
    
    public static boolean updateOpportunity = false;
    public static Final String StageName_SUSPECT = 'Suspect';
    public static Final String StageName_QA = 'Qualification/Analysis';
    public static Final String StageName_IR = 'Internal Review';
    public static Final String NPOStatus_RECALLED = 'Recalled';
    public static Final String NPOStatus_APPROVED = 'Approved';
    //Added by Sudipta for New OPS record type
    public static Final String StageName_NEW = 'New';
    //Added by Gunjari for New Request on 05/09
    public static Final String StageName_PROPOSAL ='Proposal';
    
    

}